/**
 * MINI PROFILE REPORT RENDERER
 * 
 * LAYER 3: Takes scoring payload + mini-profile JSON.
 * Renders fixed 5-page structure.
 * PDF-ready structure (easily converted to PDF later).
 */

import React from 'react';
import './MiniProfileReport.css';

export default function MiniProfileReport({ scoringPayload, miniProfile, userName = 'Participant' }) {
  // Gate debug section: only show in development
  const SHOW_DEBUG = import.meta.env.DEV;

  if (!scoringPayload || !miniProfile) {
    return <div className="report-error">Missing scoring or profile data</div>;
  }

  // Generate current date in "Month Year" format
  const now = new Date();
  const monthYear = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  return (
    <div className="mini-profile-report">
      {/* PAGE 1: COVER PAGE */}
      <Page className="page-cover">
        <div className="cover-page">
          <div className="cover-header">
            <p className="cover-label">STRATEGIC FRONT DOOR</p>
            <h1 className="cover-system-title">MORE MINDMAP SYSTEM</h1>
            <p className="cover-system-subtitle">Behavioral Intelligence Profile</p>
          </div>

          <div className="cover-main">
            <h2 className="cover-main-title">PERSONAL OPERATING PROFILE</h2>
            <p className="cover-name">{userName}</p>
            <p className="cover-date">{monthYear}</p>
          </div>

          <div className="cover-patterns">
            <div className="pattern-block">
              <p className="pattern-label">Primary Pattern</p>
              <p className="pattern-value">{miniProfile.primary_pattern}</p>
            </div>
            <div className="pattern-block">
              <p className="pattern-label">Secondary Pattern</p>
              <p className="pattern-value">{miniProfile.secondary_pattern}</p>
            </div>
          </div>

          <div className="cover-body">
            <p>
              This report analyzes how you behave under pressure, how you make decisions, how you communicate, and how you operate across real-world scenarios.
            </p>
            <p>
              It is not based on what you say about yourself.
            </p>
            <p>
              It is based on how you respond when situations become unclear, dynamic, or uncomfortable.
            </p>
          </div>

          <div className="cover-footer">
            <p className="footer-prepared">Prepared for: {userName}</p>
            <p className="footer-system">Generated by MORE MindMap System</p>
          </div>
        </div>
      </Page>

      {/* PAGE 2: DIMENSIONS & SUMMARY */}
      <Page className="page-dimensions">
        <div className="page-title">Your Behavioral Profile</div>

        <section className="dimensions-section">
          {(scoringPayload?.ranked_dimensions || scoringPayload?.ranked || []).map((dimension, idx) => (
            <DimensionBar
              key={idx}
              name={dimension.label}
              score={dimension.percent}
            />
          ))}
        </section>

        {/* NEW: PHASE 1 DOMINANCE STRUCTURE */}
        <section className="dominance-structure-section">
          <div className="dominance-title">How Your Profile Is Structured</div>
          <p className="dominance-note">{miniProfile.dominance_note}</p>

          <div className="dominance-breakdown">
            <div className="dominance-group">
              <h3 className="dominance-group-title">Primary Drivers</h3>
              <ul className="dominance-list">
                {miniProfile.dominance_structure?.primary?.map((d, i) => (
                  <li key={i}>{d.label} ({d.score}%)</li>
                ))}
              </ul>
            </div>

            <div className="dominance-group">
              <h3 className="dominance-group-title">Secondary Patterns</h3>
              <ul className="dominance-list">
                {miniProfile.dominance_structure?.secondary?.map((d, i) => (
                  <li key={i}>{d.label} ({d.score}%)</li>
                ))}
              </ul>
            </div>

            <div className="dominance-group">
              <h3 className="dominance-group-title">De-prioritized (Not Weaknesses)</h3>
              <ul className="dominance-list">
                {miniProfile.dominance_structure?.suppressed?.map((d, i) => (
                  <li key={i}>{d.label} ({d.score}%)</li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <section className="summary-section">
          <div className="summary-title">What This Means</div>
          <p className="summary-text">{miniProfile.what_this_means}</p>
        </section>
      </Page>

      {/* PAGE 3: PRIMARY & SECONDARY PATTERNS */}
      <Page className="page-patterns">
        <div className="page-title">Primary & Secondary Patterns</div>

        <section className="patterns-grid">
          <div className="pattern-card primary">
            <div className="pattern-card-label">Primary Pattern</div>
            <div className="pattern-card-value">{miniProfile.primary_pattern}</div>
          </div>

          <div className="pattern-card secondary">
            <div className="pattern-card-label">Secondary Pattern</div>
            <div className="pattern-card-value">{miniProfile.secondary_pattern}</div>
          </div>
        </section>
      </Page>

      {/* PAGE 4: HOW YOU OPERATE */}
      <Page className="page-operate">
        <div className="page-title">How You Operate</div>

        <section className="operate-sections">
          <div className="operate-subsection">
            <div className="subsection-title">How You Move</div>
            <p className="subsection-text">{miniProfile.how_you_move}</p>
          </div>

          <div className="operate-subsection">
            <div className="subsection-title">Communication Style</div>
            <p className="subsection-text">{miniProfile.communication_style}</p>
          </div>

          <div className="operate-subsection">
            <div className="subsection-title">Decision Pattern</div>
            <p className="subsection-text">{miniProfile.decision_pattern}</p>
          </div>
        </section>
      </Page>

      {/* PAGE 5: REAL WORLD APPLICATION */}
      <Page className="page-application">
        <div className="page-title">Real World Application</div>

        <section className="application-sections">
          <div className="application-subsection">
            <div className="subsection-title">Sales Behavior</div>
            <p className="subsection-text">{miniProfile.sales_behavior}</p>
          </div>

          <div className="application-subsection">
            <div className="subsection-title">Leadership</div>
            <p className="subsection-text">{miniProfile.leadership_snapshot}</p>
          </div>

          <div className="application-subsection">
            <div className="subsection-title">Friction Pattern</div>
            <p className="subsection-text">{miniProfile.friction_pattern}</p>
          </div>

          <div className="application-subsection last">
            <div className="subsection-title">Next Step</div>
            <p className="subsection-text">{miniProfile.recommended_next_step}</p>
          </div>
        </section>
      </Page>

      {/* DEBUG PAGE: Full miniProfile object + Phase 2A interpretation (DEV ONLY) */}
      {SHOW_DEBUG && (
        <Page className="page-debug">
          <div className="page-title">Debug: Full Profile Data</div>
          <div style={{ fontSize: '11px', padding: '12px', lineHeight: '1.4' }}>
            <h4 style={{ marginTop: 0 }}>Full miniProfile Object:</h4>
            <pre className="debug-json" style={{ maxHeight: '300px', overflow: 'auto' }}>
              {JSON.stringify(miniProfile, null, 2)}
            </pre>
            
            {miniProfile.written_interpretation && (
              <>
                <h4 style={{ marginTop: '20px' }}>Phase 2A: Written Interpretation</h4>
                <pre className="debug-json" style={{ maxHeight: '200px', overflow: 'auto', backgroundColor: '#f0f8ff' }}>
                  {JSON.stringify(miniProfile.written_interpretation, null, 2)}
                </pre>
              </>
            )}
            
            {miniProfile.interpreter_modifier && (
              <>
                <h4 style={{ marginTop: '20px' }}>Phase 2A: Interpreter Modifier</h4>
                <pre className="debug-json" style={{ maxHeight: '200px', overflow: 'auto', backgroundColor: '#fff5e6' }}>
                  {JSON.stringify(miniProfile.interpreter_modifier, null, 2)}
                </pre>
              </>
            )}
          </div>
        </Page>
      )}
    </div>
  );
}

/**
 * Page wrapper component
 */
function Page({ children, className = '' }) {
  return (
    <div className={`page ${className}`}>
      <div className="page-inner">
        {children}
      </div>
    </div>
  );
}

/**
 * Dimension score bar component
 */
function DimensionBar({ name, score }) {
  const percentage = Math.round(Math.min(Math.max(score || 0, 0), 100));
  
  return (
    <div className="dimension-item">
      <div className="dimension-header">
        <span className="dimension-name">{name}</span>
        <span className="dimension-score">{percentage}%</span>
      </div>
      <div className="dimension-bar-container">
        <div className="dimension-bar">
          <div
            className="dimension-bar-fill"
            style={{ width: `${percentage}%` }}
          />
        </div>
      </div>
    </div>
  );
}
